name: Update

# This is version 2 of the workflow
on:
  workflow_dispatch:  # Allow manual triggering
  label:
    types:
      - created # for test
  schedule:
      - cron: '30 16 * * *' # 00:30 Singapore time every day

permissions:
  contents: write
  issues: write 

jobs:
  update_daily_papers:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        ref: main

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Update papers
      run: |
        python main.py

    - name: Commit and push changes
      uses: github-actions-x/commit@v2.9
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        push-branch: 'main'
        commit-message: '✏️ Update papers automatically.'
        force-add: 'true'
        files: README.md .github/ISSUE_TEMPLATE.md
        name: yongfu-li
        email: liyongfu.sg@gmail.com

    - name: Create Issue
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const fs = require('fs');
          const issueContent = fs.readFileSync('.github/ISSUE_TEMPLATE.md', 'utf8');
          const titleMatch = issueContent.match(/title: (.*)/);
          const title = titleMatch ? titleMatch[1] : 'Latest Papers Update';
          
          await github.rest.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: title,
            body: issueContent,
            labels: ['documentation']
          });
